name: Style Guide Validation

on:
  workflow_call:

concurrency: style-guide-validation-${{ github.ref }}

run-name: "Validate style guides in ${{ github.ref_name }}"

jobs:
  style-guide-validation:
    name: Run Style Guide Validation
    uses: OutSystems/tk-cicd/.github/workflows/style-guides-validation.yml@main
    with:
      runner-type: "ubuntu-latest"
      markdownlint-overrides: >
        [
          { "pattern": "src/troubleshooting/incident-models/**/*.md", "config": "src/troubleshooting/incident-models/.markdownlint.json" },
          { "pattern": "src/release-notes/**/*.md", "config": "src/release-notes/.markdownlint.json" }
        ]
    secrets:
      github-token: ${{ secrets.TOOLS_PAT }}
      copilot-token: ${{ secrets.TK_COPILOT_TOKEN }}
